# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx1536m
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
#database
bannerDb="banner"
userDb="user"
peralatanDb="peralatan"
paketAcaraDb="paketAcara"
pengisiAcaraDb="pengisiAcara"
acaraDb="acara"
accountDb="account"
klikMenuDb="klikMenu"
ulasanDb="review"
listOrderDb="listOrder"
provinceDb="province"
cityDb="city"
districtDb="district"
mitraDb="mitra"
productDb="product"
orderDb="order"
bankDb="bank"
ratingDb="rating"
eventDb="event"

kycDb="kyc"
#parceler
userData="userKey"
mitraData="mitraKey"
registrationData="registrationKey"
#key
gmailKey="676533376357-ohoss370nfbnolhcf19d0k798d6pso6r.apps.googleusercontent.com"
android.useAndroidX=true
android.enableJetifier=true
#remote config key
currentVersionKey="currentVersion"
isMaintainKey="isMaintain"
playStoreUrlKey="playStoreUrl"
aboutUsKey="aboutUsUrl"
ppKey="privacyPolicyUrl"
tncKey="termAndConditionUrl"


